const DB_KEY='su-prospects-v1';
const iso=d=>new Date(d+'T12:00:00').toISOString().slice(0,10);
const today=()=>new Date().toISOString().slice(0,10);
const dateOffset=n=>{const d=new Date();d.setDate(d.getDate()+n);return iso(d)};
const seed=[
 {id:1,name:'Mariana Oliveira',phone:'(12) 99742-0819',status:'Em negociação',created:dateOffset(-8),nextContact:today(),follows:[{date:dateOffset(-2),note:'Solicitou orçamento para energia solar.',result:'Orçamento enviado'}]},
 {id:2,name:'Condomínio Vale Verde',phone:'(12) 99184-4402',status:'Novo',created:dateOffset(-3),nextContact:today(),follows:[{date:dateOffset(-3),note:'Contato recebido por indicação.',result:'Aguardando primeiro retorno'}]},
 {id:3,name:'Ricardo Mendes',phone:'(12) 98831-7534',status:'Em negociação',created:dateOffset(-13),nextContact:dateOffset(-2),follows:[{date:dateOffset(-5),note:'Visita técnica realizada.',result:'Retornar para decisão'}]},
 {id:4,name:'Clínica Bem Estar',phone:'(12) 99658-2017',status:'Fechado',created:dateOffset(-19),nextContact:'',follows:[{date:dateOffset(-4),note:'Proposta aprovada.',result:'Fechado'}]}
];
let prospects=JSON.parse(localStorage.getItem(DB_KEY)||'null')||seed;let currentFilter='all';let currentId=null;
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem(DB_KEY,JSON.stringify(prospects))}
function format(d){if(!d)return 'Sem data programada';return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(new Date(d+'T12:00:00')).replace('.','')}
function active(p){return !['Fechado','Perdido'].includes(p.status)}
function stats(){const t=today(),a=prospects.filter(active),now=new Date();return{active:a.length,today:a.filter(p=>p.nextContact===t).length,overdue:a.filter(p=>p.nextContact&&p.nextContact<t).length,closed:prospects.filter(p=>p.status==='Fechado').length,month:prospects.filter(p=>{const d=new Date(p.created+'T12:00:00');return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}).length}}
function initials(n){return n.split(' ').slice(0,2).map(x=>x[0]).join('')}
function renderDashboard(){const s=stats();$('#activeCount').textContent=s.active;$('#todayCount').textContent=s.today;$('#overdueCount').textContent=s.overdue;$('#closedCount').textContent=s.closed;$('#monthCount').textContent=`${s.month} novos neste mês`;
 $('#todayNav').textContent=s.today;$('#overdueNav').textContent=s.overdue;$('#prospectTotal').textContent=prospects.length;
 const list=prospects.filter(p=>active(p)&&p.nextContact&&p.nextContact<=today()).sort((a,b)=>a.nextContact.localeCompare(b.nextContact));$('#priorityList').innerHTML=list.length?list.map(p=>`<div class="contact-row" data-open="${p.id}"><span class="initials">${initials(p.name)}</span><span><strong>${p.name}</strong><small>${p.phone} · Próximo contato: ${format(p.nextContact)}</small></span><span class="tag ${p.nextContact<today()?'overdue':''}">${p.nextContact<today()?'ATRASADO':'HOJE'}</span></div>`).join(''):'<p class="empty">Nenhum contato pendente para hoje. Ótimo trabalho!</p>';
 const names=['Novo','Em negociação','Fechado','Perdido'],total=Math.max(prospects.length,1);$('#statusList').innerHTML=names.map(n=>{const count=prospects.filter(p=>p.status===n).length;return `<div class="status-row"><span>${n}</span><div class="bar"><i style="width:${count/total*100}%"></i></div><b>${count}</b></div>`}).join('');bindOpen();}
function renderList(){let arr=[...prospects];const q=$('#searchInput').value.toLowerCase();let f=currentFilter==='all'?$('#statusFilter').value:currentFilter;if(f==='today')arr=arr.filter(p=>active(p)&&p.nextContact===today());else if(f==='overdue')arr=arr.filter(p=>active(p)&&p.nextContact&&p.nextContact<today());else if(f!=='all')arr=arr.filter(p=>p.status===f);arr=arr.filter(p=>(p.name+p.phone).toLowerCase().includes(q));$('#prospectList').innerHTML=arr.length?arr.map(p=>`<article class="prospect-card" data-open="${p.id}"><span><strong>${p.name}</strong><small>${p.phone}</small></span><span class="status ${p.status==='Em negociação'?'negociacao':p.status.toLowerCase()}">${p.status}</span><small>${p.follows.length} follow-up${p.follows.length!==1?'s':''}</small><span class="next">Próximo: <strong>${format(p.nextContact)}</strong></span><span>›</span></article>`).join(''):'<p class="empty">Nenhum prospect encontrado.</p>';bindOpen()}
function show(view,filter='all'){currentFilter=filter;$('#dashboardView').hidden=view!=='dashboard';$('#prospectsView').hidden=view==='dashboard';$('#pageTitle').textContent=view==='dashboard'?'Visão geral':filter==='today'?'Ligar hoje':filter==='overdue'?'Follow-ups atrasados':'Prospects';$$('.nav-item').forEach(x=>x.classList.remove('active'));if(view==='dashboard')$('[data-view="dashboard"]').classList.add('active');if(view==='prospects')renderList();}
function open(id){currentId=id;const p=prospects.find(x=>x.id===id);const follows=[...p.follows].reverse();$('#detailContent').innerHTML=`<div class="detail-title"><p class="eyebrow">PROSPECT</p><h2>${p.name}</h2><p>${p.phone}</p></div><div class="detail-info"><span>Status: <b>${p.status}</b></span><span>Próximo contato: <b>${format(p.nextContact)}</b></span></div><div class="detail"><h3>Histórico de follow-ups</h3>${follows.length?follows.map(f=>`<div class="follow-item"><strong>${f.result||'Contato registrado'}</strong><p>${f.note}</p><small>${format(f.date)}</small></div>`).join(''):'<p class="empty">Ainda não há histórico.</p>'}<div class="add-follow"><h3>Registrar follow-up</h3><form id="followForm"><label>Anotação<textarea required name="note" placeholder="O que foi conversado?"></textarea></label><label>Resultado<select name="result"><option>Contato realizado</option><option>Aguardando retorno</option><option>Orçamento enviado</option><option>Visita agendada</option><option>Fechado</option><option>Perdido</option></select></label><label>Próximo contato<input required name="nextContact" type="date" value="${p.nextContact||today()}" /></label><button class="primary full">Salvar follow-up</button></form></div></div>`;openModal('detailModal');$('#followForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));p.follows.push({date:today(),...d});p.nextContact=d.nextContact;if(d.result==='Fechado')p.status='Fechado';if(d.result==='Perdido')p.status='Perdido';save();renderDashboard();renderList();open(id)};}
function bindOpen(){$$('[data-open]').forEach(x=>x.onclick=()=>open(+x.dataset.open))}function openModal(id){$('#modalBackdrop').hidden=false;$('#prospectModal').hidden=true;$('#detailModal').hidden=true;$('#'+id).hidden=false}function close(){ $('#modalBackdrop').hidden=true}
$('#newProspect').onclick=()=>openModal('prospectModal');$$('[data-close]').forEach(x=>x.onclick=close);$('#modalBackdrop').onclick=e=>{if(e.target.id==='modalBackdrop')close()};
$('#prospectForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));prospects.unshift({id:Date.now(),...d,created:today(),follows:[]});save();e.target.reset();close();renderDashboard();show('prospects')};
$$('.nav-item').forEach(x=>x.onclick=()=>x.dataset.view?show(x.dataset.view):show('prospects',x.dataset.filter));$$('[data-filter]').forEach(x=>{if(!x.classList.contains('nav-item'))x.onclick=()=>show('prospects',x.dataset.filter)});$('#searchInput').oninput=renderList;$('#statusFilter').onchange=()=>{currentFilter='all';renderList()};
$('#todayDate').textContent=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'numeric',month:'long'}).format(new Date());renderDashboard();
